### ISSUE TITLE
SeaLion-Extras.zip  32.2.1

### ISSUE THREAD

**Issue by pook52mb** [wicknix/SeaLion#1]
You might want to include the following files in the extras package
[FP-32-0r000371c1x9xA-un.dmg.zip](https://github.com/wicknix/SeaLion/files/11851393/FP-32-0r000371c1x9xA-un.dmg.zip)
[FP-32-0r000238c1x9xA-un.dmg.zip](https://github.com/wicknix/SeaLion/files/11851395/FP-32-0r000238c1x9xA-un.dmg.zip)
[FP-32-0r000238c1x9xA-ns.dmg.zip](https://github.com/wicknix/SeaLion/files/11851396/FP-32-0r000238c1x9xA-ns.dmg.zip)
The last 32-bit npapi version of Flash Player for Mac, and uninstallers for 371 and 238

**Comment by wicknix** [comment]
Hey thanks! I've added them.

**Comment by pook52mb** [comment]
I forgot about your x86_64 Linux build.  
[FP-32-0r000371c2-ns.tar.gz](https://github.com/wicknix/SeaLion/files/11873701/FP-32-0r000371c2-ns.tar.gz)
There is no uninstaller for Linux, that I am aware of.

**Comment by pook52mb** [comment]
P.S. - when you archived and renamed "flashplayer32_0r0_371_mac.dmg", the name should have been "FP-32-0r000371c2x9xA-ns.dmg.zip", as it is for c2 (64-bit) cpus only.  The uninstaller is correctly named "FP-32-0r000371c1x9xA-un.dmg.zip" as it is for c1 and c2, npapi and ppapi versions

**Comment by wicknix** [comment]
Got it. Thanks. Will be fixed in the next release which should be later today.
