### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by awilfox** [wicknix/SeaLion#2]
Hi there.  I'm trying to poke at SeaLion on Adélie Linux, which is a Linux distribution for PowerPC (and x86 and Arm) systems.  Python 2.7 is quite dead upstream and there is no Python 2 package at all for Adélie.  It looks like upstream UXP supports Python 3; is there any plan to support Python 3 for building SeaLion?

**Comment by wicknix** [comment]
UXP's build system requires 2.7. See [here](https://forum.palemoon.org/viewtopic.php?f=62&t=30537&p=245488&hilit=python+3#p245462) and [here](https://developer.palemoon.org/build/linux/)

Python is relatively easy to compile. I'd suggest maybe giving that a whirl as i highly doubt upstream UXP are making the switch any time soon, and my knowledge of python is non existent.

**Comment by mattatobin** [comment]
Word has it that tauthon is also an option but it being used primarily on the linux is less tested.

**Comment by wicknix** [comment]
@awilfox
I see you caved and built py2 to build Arctic Fox. Any thoughts on trying SeaLion again? It's a much better browser that actually works with most modern sites like github, discord, etc. 

To build. Download latest source. Extract.
Download the latest UXP source: https://repo.palemoon.org/MoonchildProductions/UXP
Extract it. Rename the extracted 'uxp' directory to 'platform'. Copy platform in to SeaLions directory.
Fix up .mozconfig for Linux (devtools is not supported. leave disabled) and ./mach build && ./mach package

**Comment by awilfox** [comment]
I can take a look at this after our Beta 6 is released.  Would you recommend SeaLion or BrassMonkey (so that it can be available to replace Thunderbird on ppc32 as well)?

Does the UXP source version need to correspond to the SeaLion version, or is it better to use the latest release version even though SeaLion is not the same (I see UXP 33.5.0 is released)?

**Comment by wicknix** [comment]
I'd start with SeaLion. Seems most people prefer it over the full suite for some reason, and i have to make a few changes to BrassMonkey for seamless packaging on PPC Linux. Right now it packages the wrong endianess for ICU.dat, and you have to manually swap out the files after ./mach package finishes. I fixed that in SeaLion already.

For an email client SeaLion's source includes SeaMail (fork of thunderbird), but it must be built separately.

I try to follow UXP's release cycle fairly close. I mainly stick to the 'bug fix' release schedule. My versioning closely follows theirs. So 33.4.0 used 33.4.1 UXP sources. Christian Z aka Xeno74 (who builds these for various PPC Linux distros) uses UXP's current 'master' branch, which is fine with me. The differences would be minimal and not really noticeable to the end user. SeaLions UI has been at a stable state for awhile now, and the only changes i make now are to version.txt. The UXP devs do all the hard work. I just build on top of their "unified XUL platform".

**Comment by wicknix** [comment]
@awilfox : Christian (xeno74) has built SeaLion for 32-bit ppc Adelie.

https://github.com/chzigotzky/Web-Browsers-and-Suites-for-Linux-PPC/releases/tag/SeaLion_33.5.1
