### ISSUE TITLE
request, detect tauthon

### ISSUE THREAD

**Issue by FrostKnight** [wicknix/SeaLion#8]
tauthon is a python 2 but continued. Hyperbola has it instead of python2.7

I don't know if you detect it already though.

I have interest in building this from source. Can you tell me where you put the instructions to do so?

Also, how is it done, etc... just asking.

**Comment by wicknix** [comment]
git clone https://github.com/wicknix/SeaLion.git ./
git submodule init && git submodule update
git checkout release && git submodule update

Then follow the Pale Moon build instructions: https://developer.palemoon.org/build/linux/
You will need to modify the included .mozconfig for Linux and remove the MacOS stuff. Use Pale Moon's config for reference.

**Comment by FrostKnight** [comment]
> Create a directory to build sealion, then cd to it, then: git clone https://github.com/wicknix/SeaLion.git ./ git submodule init && git submodule update git checkout release && git submodule update
> 
> Then follow the Pale Moon build instructions: https://developer.palemoon.org/build/linux/ You will need to modify the included .mozconfig for Linux and remove the MacOS stuff. Use Pale Moon's config for reference.

One problem, I did the first two things but on the last one, I ran into this error:

error: pathspec 'release' did not match any file(s) known to git

**Comment by wicknix** [comment]
Ahh, ok. You could do it manually i guess. Download the [latest UXP](https://repo.palemoon.org/MoonchildProductions/UXP.git) and unpack it. Once extracted it'll be in a directory called "uxp". Just rename that directory to "platform" and place it in the sealion directory. Now just follow the Pale Moon Linux build instructions.

**Comment by FrostKnight** [comment]
> Ahh, ok. You could do it manually i guess. Download the [latest UXP](https://repo.palemoon.org/MoonchildProductions/UXP/archive/master.tar.gz) and unpack it. Once extracted there should be a directory called "uxp". Just rename that directory to "platform" and place it in the sealion directory. Now just follow the Pale Moon Linux build instructions.

[Debug-info.txt](https://github.com/user-attachments/files/17131273/Debug-info.txt)


I ran into some bugs here.

Btw, can you make it so tauthon is detected? Its basically a continued version of python2.7

This would help a lot.

**Comment by wicknix** [comment]
Disable devtools in your mozconfig. SeaLion doesn't support it.

**Comment by wicknix** [comment]
The only way this will support tauthon is if pale moon implements it since it uses uxp for it's backend.

**Comment by FrostKnight** [comment]
> The only way this will support tauthon is if pale moon implements it since it uses uxp for it's backend.

Well for now its fine this could be locked for now. I figured out how to build it. :)
